export default copy = {
    names: [
        'Adam',
        'Carl',
        'Christer A',
        'Christer S',
        'Erik N',
        'Ivan',
        'Ivona',
        'Joakim',
        'Johannes',
        'Lars-Erik',
        'Matewos',
        'Miriam',
        'Niklas',
        'Ola',
        'Rickard',
        'Robert',
    ],
    stepTexts: [
        'Create a new array containing 8 persons. Each person should have the properties name, age and height. At least 3 persons must be taller than 2 meters.',
        'Create another array containing 4 persons, each also having the properties name, age and height.',
        'Combine the two arrays.',
        'Using the filter() method, create a new array that only includes the persons taller than 2 meters.',
        'Using the forEach() method, log all persons taller than 2 meters to the console.',
    ],
    instruction: '* Click on a stack for more details.',
};
